### ISSUE TITLE
Autofeed feed when?

### ISSUE THREAD

**Issue by YumeHaru** [menma1234/gbf-itemmagic#2]
Hi,
*I'm lookin foard to that feature because it's really a pain to select everytime the same weapon you want to upgrade then select bunch of 20 fooders. I wish tha you feature let us autofeed until it's full then give us a pop un message that it can't be level up anymore.

Also i would be could that the autofeed feature would integrate skilling up weapns skills, you can follow that guide, it's 100% accurate: http://gbf-english.proboards.com/thread/595/#4

**Comment by menma1234** [comment]
I'm really lazy and I've kinda retired from GBF at this point, so it's really up in the air. I've got other real life commitments, so I have no idea to be quite honest. 

As for the skill level thing, this whole extension was more of a crude thing to save clicks so I doubt it'd get that smart even if I did implement this.

**Comment by menma1234** [comment]
Going to close this since things are a lot easier now with grails in place so probably not needed in the extension.
